starting worker pid=23172 on localhost:11948 at 13:52:50.349
starting worker pid=15948 on localhost:11948 at 13:52:50.349
starting worker pid=25452 on localhost:11948 at 13:52:50.357
starting worker pid=6112 on localhost:11948 at 13:52:50.360
starting worker pid=24364 on localhost:11948 at 13:52:50.362
starting worker pid=6192 on localhost:11948 at 13:52:50.370
starting worker pid=12724 on localhost:11948 at 13:52:50.377
starting worker pid=21472 on localhost:11948 at 13:52:50.378
starting worker pid=21796 on localhost:11948 at 13:52:50.382
starting worker pid=25708 on localhost:11948 at 13:52:50.382
starting worker pid=7696 on localhost:11948 at 13:52:50.390
starting worker pid=5340 on localhost:11948 at 13:52:50.395
starting worker pid=12700 on localhost:11948 at 13:52:50.399
starting worker pid=19616 on localhost:11948 at 13:52:50.404
starting worker pid=24856 on localhost:11948 at 13:52:50.406
starting worker pid=13752 on localhost:11948 at 13:52:50.410
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
